version: "3"

services:
        nginx:
                image: nginx
                container_name: nginx
                volumes:
                        - ${MOUNT_POINT}/nginx/templates:/etc/nginx/templates
                ports:
                        - "3000:80"
                environment:
                        - NGINX_HOST=sautron.io
                        - NGINX_PORT=80
        transmission:
                image: linuxserver/transmission
                container_name: transmission
                restart: always
                network_mode: host
                ports:
                        - 9091:9091
                        - 51413:51413
                        - 51413:51413/udp
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${MOUNT_POINT}/transmission/config:/config
                        - ${MOUNT_POINT}/transmission/downloads:/downloads
                        - ${MOUNT_POINT}/transmission/watch:/watch
        plex:
                image: linuxserver/plex
                container_name: plex
                restart: always
                ports:
                        - 32400:32400
                        - 32400:32400/udp
                        - 32469:32469
                        - 32469:32469/udp
                        - 5353:5353/udp
                        - 1900:1900/udp
                network_mode: host
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${MOUNT_POINT}/plex/config:/config
                        - ${MOUNT_POINT}/plex/movies:/movies
                        - ${MOUNT_POINT}/plex/tvshows:/tvshows
                        - ${MOUNT_POINT}/plex/transcode:/transcode
        plexpy:
                 image: linuxserver/plexpy
                 container_name: plexpy
                 ports:
                        - 8181:8181
                 environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                 volumes:
                        - ${MOUNT_POINT}/plexpy/config:/config
                        - ${MOUNT_POINT}/plexpy/logs:/logs
        sickchill:
                image: sickchill/sickchill
                container_name: sickchill
                network_mode: host
                restart: always
                ports:
                        - 8081:8081
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${MOUNT_POINT}/sickchill/config:/config
                        - ${MOUNT_POINT}/sickchill/downloads:/downloads
                        - ${MOUNT_POINT}/sickchill/tv:/tv
        couchpotato:
                image: linuxserver/couchpotato
                container_name: couchpotato
                network_mode: host
                restart: always
                ports:
                        - 5050:5050
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                        - UMASK_SET=022
                volumes:
                        - ${MOUNT_POINT}/couchpotato/config:/config
                        - ${MOUNT_POINT}/couchpotato/downloads:/downloads
                        - ${MOUNT_POINT}/couchpotato/movies:/movies
                restart: unless-stopped
