version: "3"

services:
        nginx:
                image: nginx
                container_name: nginx
                volumes:
                        - ${MOUNT_SERVICES}/nginx/templates:/etc/nginx/templates
                ports:
                        - 80:80
                environment:
                        - NGINX_HOST=sautron.io
                        - NGINX_PORT=80
        transmission:
                image: lscr.io/linuxserver/transmission:latest
                container_name: transmission
                restart: unless-stopped
                ports:
                        - 9091:9091
                        - 51413:51413
                        - 51413:51413/udp
                expose:
                        - 9091
                environment:
                        - USER=${TRANSMISSION_USERNAME}
                        - PASS=${TRANSMISSION_PASSWORD}
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${MOUNT_SERVICES}/transmission/config:/config
                        - ${MOUNT_MEDIA}/downloads:/downloads
                        - ${MOUNT_MEDIA}/movies:/movies
                        - ${MOUNT_MEDIA}/tv:/tv
        plex:
                image: lscr.io/linuxserver/plex:latest
                container_name: plex
                restart: unless-stopped
                ports:
                        - 32400:32400
                        - 1900:1900/udp
                        - 3005:3005
                        - 5353:5353/udp
                        - 8324:8324
                        - 32410:32410/udp
                        - 32412:32412/udp
                        - 32413:32413/udp
                        - 32414:32414/udp
                        - 32469:32469
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - VERSION=docker
                        - TZ=${TZ}
                        - PLEX_CLAIM=${PLEX_CLAIM}
                volumes:
                        - ${MOUNT_SERVICES}/plex/config:/config
                        - ${MOUNT_MEDIA}/movies:/movies
                        - ${MOUNT_MEDIA}/tv:/tv
        scheduler:
                image: mcuadros/ofelia:latest
                container_name: scheduler
                depends_on:
                        - plextraktsync
                command: daemon --docker
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock:ro
                labels:
                        ofelia.job-run.plextraktsync.schedule: "@every 1h"
                        ofelia.job-run.plextraktsync.container: "plextraktsync"
                        ofelia.job-run.plextraktsync.command: "sync"
        plextraktsync:
                image: ghcr.io/taxel/plextraktsync
                container_name: plextraktsync
                restart: on-failure:2
                volumes:
                        - ${MOUNT_SERVICES}/plextractsync:/app/config
        jellyfin:
                image: lscr.io/linuxserver/jellyfin:latest
                container_name: jellyfin
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${MOUNT_SERVICES}/jellyfin/config:/config
                        - ${MOUNT_MEDIA}/po:/po
                ports:
                        - 8096:8096
                        - 8920:8920 #optional
                        - 7359:7359/udp #optional
                        - 1901:1900/udp #optional
                restart: unless-stopped
        sickchill:
                image: lscr.io/linuxserver/sickchill:latest
                container_name: sickchill
                restart: always
                ports:
                        - 8081:8081
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${MOUNT_SERVICES}/sickchill/config:/config
                        - ${MOUNT_MEDIA}/downloads:/downloads
                        - ${MOUNT_MEDIA}/tv:/tv
        couchpotato:
                image: lscr.io/linuxserver/couchpotato
                container_name: couchpotato
                restart: always
                ports:
                        - 5050:5050
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                        - UMASK_SET=022
                volumes:
                        - ${MOUNT_SERVICES}/couchpotato/config:/config
                        - ${MOUNT_MEDIA}/downloads:/downloads
                        - ${MOUNT_MEDIA}/movies:/movies

