version: "3"

services:
        nginx:
                image: nginx
                container_name: nginx
                network_mode: host
                volumes:
                        - ${MOUNT_POINT}/services/nginx/templates:/etc/nginx/templates
                ports:
                        - 80:80
                environment:
                        - NGINX_HOST=sautron.io
                        - NGINX_PORT=80
        transmission:
                image: linuxserver/transmission
                container_name: transmission
                restart: always
                network_mode: host
                ports:
                        - 9091:9091
                        - 51413:51413
                        - 51413:51413/udp
                environment:
                        - USER=${TRANSMISSION_USERNAME}
                        - PASS=${TRANSMISSION_PASSWORD}
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${MOUNT_POINT}/services/transmission/config:/config
                        - ${MOUNT_POINT}/downloads:/downloads
        plex:
                image: linuxserver/plex
                container_name: plex
                restart: always
                network_mode: host
                ports:
                        - 32400:32400
                        - 32400:32400/udp
                        - 32469:32469
                        - 32469:32469/udp
                        - 5353:5353/udp
                        - 1900:1900/udp
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${MOUNT_POINT}/services/plex/config:/config
                        - ${MOUNT_POINT}/media/movies:/movies
                        - ${MOUNT_POINT}/media/tvshows:/tvshows
                        - ${MOUNT_POINT}/../mnp-s/data:/po
                        - ${MOUNT_POINT}/services/plex/transcode:/transcode
        plexpy:
                image: linuxserver/plexpy
                container_name: plexpy
                network_mode: host
                ports:
                        - 8181:8181
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${MOUNT_POINT}/services/plexpy/config:/config
                        - ${MOUNT_POINT}/services/plexpy/logs:/logs
        sickchill:
                image: sickchill/sickchill:master
                container_name: sickchill
                network_mode: host
                restart: always
                ports:
                        - 8081:8081
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${MOUNT_POINT}/services/sickchill/config.ini:/data/config.ini
                        - ${MOUNT_POINT}/downloads:/downloads
                        - ${MOUNT_POINT}/media/tvshows:/tv
        couchpotato:
                image: linuxserver/couchpotato
                container_name: couchpotato
                network_mode: host
                restart: always
                ports:
                        - 5050:5050
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                        - UMASK_SET=022
                volumes:
                        - ${MOUNT_POINT}/services/couchpotato/config:/config
                        - ${MOUNT_POINT}/downloads:/downloads
                        - ${MOUNT_POINT}/media/movies:/movies
